In [33]:
# pandas is python lib

# pandas lib used of data manupulation

# how to import

import pandas as pd

In [34]:
dicts = {

    "Name" : ["Salman Khan","Ranbir","Ajay devgan","Ram charan","Prabhas"],
    "Age"  :[61,22,33,43,54],
    "Height" : [5.6,5.1,6.4,7.2,5.1],
    "Salary" : [1000,2323,343344,2222,2233]

}

In [35]:
# method 1: DataFrame --- convert the data into Table form

df=pd.DataFrame(dicts)
df

          Name  Age  Height  Salary
0  Salman Khan   61     5.6    1000
1       Ranbir   22     5.1    2323
2  Ajay devgan   33     6.4  343344
3   Ram charan   43     7.2    2222
4      Prabhas   54     5.1    2233

In [36]:
# Load the dataset

df=pd.read_csv("D:\\Data science\\Datasets\\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [37]:
# method 3: head() --- top five  rows display
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [38]:
# method 4: tail() last five rows

df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [39]:
# method 5 : sample() --- display random rows

df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3,0

In [40]:
# method 6 : shape check the size the datasets
df.shape

(303, 14)

In [41]:
# method 7 : info() check information of datasets

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [42]:
# method 8 : columns() check the columns name
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [43]:
# method 9: describe() startistical summery of the numerical column
df.describe

<bound method NDFrame.describe of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [44]:
# method 10 : isnull() check the missing value

df.isnull

<bound method DataFrame.isnull of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [45]:
# method 11 : select the single column

age=df["age"]

In [46]:
age

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [47]:
# method 12: select the multiple columns

two_col=df[["age","sex"]]
two_col

     age  sex
0     63    1
1     37    1
2     41    0
3     56    1
4     57    0
..   ...  ...
298   57    0
299   45    1
300   68    1
301   57    1
302   57    0

[303 rows x 2 columns]

In [48]:
# method 13 : value_counts() check the specific value count

df['age'].value_counts(dropna = True)

age
58    19
57    17
54    16
59    14
52    13
51    12
62    11
60    11
44    11
56    11
64    10
41    10
63     9
67     9
65     8
43     8
45     8
55     8
42     8
61     8
53     8
46     7
48     7
66     7
50     7
49     5
47     5
70     4
39     4
35     4
68     4
38     3
71     3
40     3
69     3
34     2
37     2
29     1
74     1
76     1
77     1
Name: count, dtype: int64

In [49]:
# method 14 : copy the datasets into another variable
df2=df.copy()

In [50]:
df2.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [51]:
# method 15 : drop() = drop the columns

df.drop("age",axis = 1)

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [52]:
# method 17 :drop_duplicates drop duplicated rows
df.drop_duplicates(inplace= True)

In [53]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [54]:
# method 18 : drop_duplicate(subset =["col_name"])  : specific column rows drop

df.drop_duplicates(subset = ["oldpeak"],inplace = True)

In [55]:
# method 19 : rename : change the columns names

df.rename(columns = {"target":"Result"},inplace=True)

In [56]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'Result'],
      dtype='object')

In [57]:
for i in df.columns:
    c=i.title()
    print()

In [58]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
42,45,1,0,104,208,0,0,148,1,3.0,1,0,2,1
76,51,1,2,125,245,1,0,166,0,2.4,1,0,2,1
97,52,1,0,108,233,1,1,147,0,0.1,2,3,3,1
98,43,1,2,130,315,0,1,162,0,1.9,2,1,2,1
101,59,1,3,178,270,0,0,145,0,4.2,0,0,3,1
108,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
169,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3,0
178,43,1,0,120,177,0,0,120,1,2.5,1,0,3,0
187,54,1,0,124,266,0,0,109,1,2.2,1,1,3,0
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3,0
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3,0
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
221,55,1,0,140,217,0,1,111,1,5.6,0,0,3,0
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0
244,56,1,0,132,184,0,0,105,1,2.1,1,1,1,0
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0

In [59]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2,1
42,45,1,0,104,208,0,0,148,1,3.0,1,0,2,1
76,51,1,2,125,245,1,0,166,0,2.4,1,0,2,1
97,52,1,0,108,233,1,1,147,0,0.1,2,3,3,1
98,43,1,2,130,315,0,1,162,0,1.9,2,1,2,1
101,59,1,3,178,270,0,0,145,0,4.2,0,0,3,1
108,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2,1
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
169,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3,0
178,43,1,0,120,177,0,0,120,1,2.5,1,0,3,0
187,54,1,0,124,266,0,0,109,1,2.2,1,1,3,0
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3,0
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3,0
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
221,55,1,0,140,217,0,1,111,1,5.6,0,0,3,0
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0
244,56,1,0,132,184,0,0,105,1,2.1,1,1,1,0
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3,0
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0

In [61]:
df.columns = map(lambda x: x.title(),df.columns)

In [62]:
df.columns

Index(['Age', 'Sex', 'Cp', 'Trestbps', 'Chol', 'Fbs', 'Restecg', 'Thalach',
       'Exang', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Result'],
      dtype='object')

In [63]:
df.head()

,Age,Sex,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [64]:
# method 20 : astype() change the datatype of columns

df['Oldpeak'].astype("int")

0      2
1      3
2      1
3      0
4      0
5      0
6      1
7      0
8      0
9      1
10     1
11     0
13     1
14     1
17     2
18     1
42     3
76     2
97     0
98     1
101    4
108    1
116    2
125    0
143    0
147    0
167    3
169    3
173    3
178    2
187    2
193    2
195    3
204    6
220    4
221    5
240    2
244    2
259    3
291    4
Name: Oldpeak, dtype: int64

In [70]:
age = ["12","23","34","45","su23","a1","11"]

# method 21 : to_numeric - number string convert into number

age = pd.to_numeric(age, errors='coerce')
type(age)

numpy.ndarray

In [ ]:
# method 21 : fillna("value")  - fill the missing value

# df.fillna(0,inplace = True)

# syntax :df['column'] = df['column'].fillna("value")

df['Oldpeak'] = df['Oldpeak'].fillna()

In [77]:
a = 2.3
a = int(a)

a = [1,2,3,4,5,6,7,8]

med_a = int(9/2)
med_a

4

In [86]:
old_mean=int(df['Oldpeak'].mean())
old_mean

2