In [1]:
# ==========================================
# STEP 1 : Import Pandas
# ==========================================
import pandas as pd

# ==========================================
# STEP 2 : Load Excel Dataset
# ==========================================
df = pd.read_excel(r"D:\Data science\Datasets\practice_dataset.xlsx",
                   sheet_name="Sheet1")

df

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
0,NaN,Michael Foster,Twenty Five,female,IT,Bangalore,9999999,2022/12/14,4.9,Fresher
1,EMP0109,Daniel Brown,45 years,male,Marketing,Chennai,8888888,2023/03/15,Poor,10 years
2,NaN,Zachary Rowe,NaN,F,Finance,Hyderabad,7777777,2024/08/16,Excellent,10 years
3,EMP0088,Jason Perry,45,F,HR,NaN,6666666,Not Available,Excellent,NaN
4,NaN,Danny Payne,45 years,Unknown,Finance,Delhi,5555555,2023/02/14,NaN,Fresher
...,...,...,...,...,...,...,...,...,...,...
1027,emp-466,Elizabeth Gonzalez,45 years,male,Finance,Chennai,₹70000,15-01-2025,Poor,12
1028,NaN,Ryan Franklin,NaN,Unknown,IT,Chennai,₹70000,15-09-2022,4.3,2
1029,NaN,Richard Gilbert,NaN,NaN,HR,Bangalore,NaN,02/12/2024,NaN,10 years
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,NaN,4444444,NaN,NaN,NaN

In [2]:
df

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
0,NaN,Michael Foster,Twenty Five,female,IT,Bangalore,9999999,2022/12/14,4.9,Fresher
1,EMP0109,Daniel Brown,45 years,male,Marketing,Chennai,8888888,2023/03/15,Poor,10 years
2,NaN,Zachary Rowe,NaN,F,Finance,Hyderabad,7777777,2024/08/16,Excellent,10 years
3,EMP0088,Jason Perry,45,F,HR,NaN,6666666,Not Available,Excellent,NaN
4,NaN,Danny Payne,45 years,Unknown,Finance,Delhi,5555555,2023/02/14,NaN,Fresher
...,...,...,...,...,...,...,...,...,...,...
1027,emp-466,Elizabeth Gonzalez,45 years,male,Finance,Chennai,₹70000,15-01-2025,Poor,12
1028,NaN,Ryan Franklin,NaN,Unknown,IT,Chennai,₹70000,15-09-2022,4.3,2
1029,NaN,Richard Gilbert,NaN,NaN,HR,Bangalore,NaN,02/12/2024,NaN,10 years
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,NaN,4444444,NaN,NaN,NaN

In [3]:
df.head()

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
0,NaN,Michael Foster,Twenty Five,female,IT,Bangalore,9999999,2022/12/14,4.9,Fresher
1,EMP0109,Daniel Brown,45 years,male,Marketing,Chennai,8888888,2023/03/15,Poor,10 years
2,NaN,Zachary Rowe,NaN,F,Finance,Hyderabad,7777777,2024/08/16,Excellent,10 years
3,EMP0088,Jason Perry,45,F,HR,NaN,6666666,Not Available,Excellent,NaN
4,NaN,Danny Payne,45 years,Unknown,Finance,Delhi,5555555,2023/02/14,NaN,Fresher

In [4]:
df.tail()

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
1027,emp-466,Elizabeth Gonzalez,45 years,male,Finance,Chennai,₹70000,15-01-2025,Poor,12
1028,NaN,Ryan Franklin,NaN,Unknown,IT,Chennai,₹70000,15-09-2022,4.3,2
1029,NaN,Richard Gilbert,NaN,NaN,HR,Bangalore,NaN,02/12/2024,NaN,10 years
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,NaN,4444444,NaN,NaN,NaN

In [5]:
df.sample()

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
988,NaN,Jacqueline Williams,45 years,Unknown,IT,Pune,135132,03-10-2021,NaN,NaN

In [6]:
df.shape

(1032, 10)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp ID             703 non-null    object
 1   Full Name          973 non-null    object
 2   AGE                780 non-null    object
 3   Gender             835 non-null    object
 4   Department         900 non-null    object
 5   City               888 non-null    object
 6   Salary             832 non-null    object
 7   Joining Date       810 non-null    object
 8   Performance Score  794 non-null    object
 9   Experience         778 non-null    object
dtypes: object(10)
memory usage: 80.8+ KB

In [8]:
df.columns

Index(['Emp ID ', 'Full Name', 'AGE', 'Gender ', 'Department', 'City',
       'Salary ', 'Joining Date', 'Performance Score', 'Experience'],
      dtype='object')

In [9]:
df.columns = df.columns.str.strip()

df.columns

Index(['Emp ID', 'Full Name', 'AGE', 'Gender', 'Department', 'City', 'Salary',
       'Joining Date', 'Performance Score', 'Experience'],
      dtype='object')

In [10]:
df.describe()

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
count,703,973,780,835,900,888,832,810,794,778
unique,683,930,44,5,7,6,228,551,42,23
top,EMP0660,David Thomas,45 years,Unknown,HR,Delhi,"1,20,000",Not Available,Excellent,Fresher
freq,2,2,256,175,145,162,207,212,277,263

In [11]:
df.isnull().sum()

Emp ID               329
Full Name             59
AGE                  252
Gender               197
Department           132
City                 144
Salary               200
Joining Date         222
Performance Score    238
Experience           254
dtype: int64

In [12]:
age = df["AGE"]

age.head()

0    Twenty Five
1       45 years
2            NaN
3             45
4       45 years
Name: AGE, dtype: object

In [13]:
two_col = df[["AGE","Gender"]]

two_col.head()

           AGE   Gender
0  Twenty Five   female
1     45 years     male
2          NaN        F
3           45        F
4     45 years  Unknown

In [14]:
df["Experience"].value_counts(dropna=True)

Experience
Fresher     263
10 years    258
14           19
17           18
3            16
12           15
0            15
15           15
11           14
9            14
10           14
13           13
4            12
16           12
18           12
7            11
19           10
5             9
20            8
8             8
6             8
2             7
1             7
Name: count, dtype: int64

In [15]:
df2 = df.copy()

df2.head()

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
0,NaN,Michael Foster,Twenty Five,female,IT,Bangalore,9999999,2022/12/14,4.9,Fresher
1,EMP0109,Daniel Brown,45 years,male,Marketing,Chennai,8888888,2023/03/15,Poor,10 years
2,NaN,Zachary Rowe,NaN,F,Finance,Hyderabad,7777777,2024/08/16,Excellent,10 years
3,EMP0088,Jason Perry,45,F,HR,NaN,6666666,Not Available,Excellent,NaN
4,NaN,Danny Payne,45 years,Unknown,Finance,Delhi,5555555,2023/02/14,NaN,Fresher

In [16]:
df.drop("AGE", axis=1)

,Emp ID,Full Name,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
0,NaN,Michael Foster,female,IT,Bangalore,9999999,2022/12/14,4.9,Fresher
1,EMP0109,Daniel Brown,male,Marketing,Chennai,8888888,2023/03/15,Poor,10 years
2,NaN,Zachary Rowe,F,Finance,Hyderabad,7777777,2024/08/16,Excellent,10 years
3,EMP0088,Jason Perry,F,HR,NaN,6666666,Not Available,Excellent,NaN
4,NaN,Danny Payne,Unknown,Finance,Delhi,5555555,2023/02/14,NaN,Fresher
...,...,...,...,...,...,...,...,...,...
1027,emp-466,Elizabeth Gonzalez,male,Finance,Chennai,₹70000,15-01-2025,Poor,12
1028,NaN,Ryan Franklin,Unknown,IT,Chennai,₹70000,15-09-2022,4.3,2
1029,NaN,Richard Gilbert,NaN,HR,Bangalore,NaN,02/12/2024,NaN,10 years
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,4444444,NaN,NaN,NaN

In [17]:
df.drop_duplicates(inplace=True)

df.shape

(1004, 10)

In [18]:
df.drop_duplicates(subset=["Department"], inplace=True)

df

,Emp ID,Full Name,AGE,Gender,Department,City,Salary,Joining Date,Performance Score,Experience
0,NaN,Michael Foster,Twenty Five,female,IT,Bangalore,9999999,2022/12/14,4.9,Fresher
1,EMP0109,Daniel Brown,45 years,male,Marketing,Chennai,8888888,2023/03/15,Poor,10 years
2,NaN,Zachary Rowe,NaN,F,Finance,Hyderabad,7777777,2024/08/16,Excellent,10 years
3,EMP0088,Jason Perry,45,F,HR,NaN,6666666,Not Available,Excellent,NaN
5,EMP0235,Carly Green,45 years,male,Sales,Hyderabad,4444444,08/03/2022,Poor,Fresher
9,EMP0535,April Alexander,45 years,female,NaN,Pune,999999,09/21/2023,Excellent,Fresher
10,EMP0919,Walter Burnett,45 years,male,AI,Pune,₹70000,Not Available,Excellent,Fresher
12,NaN,William Hogan,NaN,M,Data Science,NaN,"1,20,000",12/14/2022,1.8,14

In [19]:
df.rename(columns={"AGE":"Age"}, inplace=True)

df.columns

Index(['Emp ID', 'Full Name', 'Age', 'Gender', 'Department', 'City', 'Salary',
       'Joining Date', 'Performance Score', 'Experience'],
      dtype='object')

In [20]:
import pandas as pd

df = pd.read_excel(
    r"D:\Data science\Datasets\practice_dataset.xlsx",
    sheet_name="Sheet1"
)

df.head()

df.columns = df.columns.str.strip()

df.head()
df.tail()
df.sample()

df.shape

df.info()

df.columns

df.describe()

df.isnull().sum()

age = df["AGE"]

two_col = df[["AGE","Gender"]]

df["Experience"].value_counts(dropna=True)

df2 = df.copy()

df.drop("AGE", axis=1)

df.drop_duplicates(inplace=True)

df.drop_duplicates(subset=["Department"], inplace=True)

df.rename(columns={"AGE":"Age"}, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp ID             703 non-null    object
 1   Full Name          973 non-null    object
 2   AGE                780 non-null    object
 3   Gender             835 non-null    object
 4   Department         900 non-null    object
 5   City               888 non-null    object
 6   Salary             832 non-null    object
 7   Joining Date       810 non-null    object
 8   Performance Score  794 non-null    object
 9   Experience         778 non-null    object
dtypes: object(10)
memory usage: 80.8+ KB