In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel("D:\Data science\Datasets\Pandas_Practice_Dataset.xlsx")
print("Raw columns:", df.columns.tolist())
df.head(3)

Raw columns: ['Customer', 'Name', 'Age', 'Unnamed: 3', 'Gender', 'City', 'Salary', 'Experienc', 'Departme', 'Joining_D', 'Performa']

,Customer,Name,Age,Unnamed: 3,Gender,City,Salary,Experienc,Departme,Joining_D,Performa
0,1.0,Amit,NaN,43.0,Female,Chennai,48886,26.0,NaN,2020-02-09 00:00:00,90.81
1,2.0,Kiran,NaN,35.0,F,Bengaluru,"₹75,196",14.0,NaN,2020-04-01 00:00:00,70.98
2,3.0,Neha,NaN,44.0,M,NaN,111831,28.0,IT,2020-06-23 00:00:00,65.04

In [3]:
# 'Age' column is fully empty; the real age values are in 'Unnamed: 3'.
df = df.drop(columns=['Age']).rename(columns={'Unnamed: 3': 'Age'})

# Rename truncated column headers to full, readable names
df = df.rename(columns={
    'Customer': 'Customer_ID',
    'Experienc': 'Experience',
    'Departme': 'Department',
    'Joining_D': 'Joining_Date',
    'Performa': 'Performance_Score'
})

# Reorder columns
df = df[['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary',
          'Experience', 'Department', 'Joining_Date', 'Performance_Score']]

print(df.columns.tolist())
df.head()

['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Experience', 'Department', 'Joining_Date', 'Performance_Score']

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score
0,1.0,Amit,43.0,Female,Chennai,48886,26.0,NaN,2020-02-09 00:00:00,90.81
1,2.0,Kiran,35.0,F,Bengaluru,"₹75,196",14.0,NaN,2020-04-01 00:00:00,70.98
2,3.0,Neha,44.0,M,NaN,111831,28.0,IT,2020-06-23 00:00:00,65.04
3,79.0,Sneha,38.0,F,HYD,72973,3.0,HR,2021-01-0,65.51
4,5.0,Rohit,46.0,F,hyd,64961,17.0,hr,2020-03-28 00:00:00,98.68

In [4]:
df.head(10)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score
0,1.0,Amit,43.0,Female,Chennai,48886,26.0,NaN,2020-02-09 00:00:00,90.81
1,2.0,Kiran,35.0,F,Bengaluru,"₹75,196",14.0,NaN,2020-04-01 00:00:00,70.98
2,3.0,Neha,44.0,M,NaN,111831,28.0,IT,2020-06-23 00:00:00,65.04
3,79.0,Sneha,38.0,F,HYD,72973,3.0,HR,2021-01-0,65.51
4,5.0,Rohit,46.0,F,hyd,64961,17.0,hr,2020-03-28 00:00:00,98.68
5,6.0,Pooja,28.0,F,Delhi,38199,27.0,hr,2019-03-02 00:00:00,96.75
6,7.0,Neha,59.0,Female,Bangalore,31152,27.0,NaN,2020-12-31 00:00:00,68.06
7,8.0,NaN,22.0,M,Chennai,"₹58,457",5.0,it,2024-10-0,96.17
8,9.0,Pooja,-5.0,Unknown,NaN,93372,5.0,Finance,2020-07-12 00:00:00,79.14
9,10.0,Kiran,58.0,F,NaN,59378,17.0,IT,2020-04-11 00:00:00,98.43

In [5]:
df.tail(10)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score
37,79.0,Pooja,NaN,NaN,hyd,110730,28.0,it,2022-01-01 00:00:00,62.01
38,38.0,Priya,NaN,F,Bangalore,29240,25.0,Finance,2020-08-01 00:00:00,56.06
39,39.0,Anita,NaN,M,Mumbai,63004,6.0,Sales,2019-09-0,45.02
40,40.0,Sneha,NaN,Unknown,HYD,69105,10.0,it,2020-09-14 00:00:00,91.66
41,41.0,Ravi,NaN,Unknown,NaN,82768,18.0,Marketing,2020-11-13 00:00:00,96.78
42,42.0,Arjun,NaN,Male,Pune,81014,23.0,HR,2020-04-02 00:00:00,43.50
43,43.0,Sneha,NaN,F,Bangalore,55248,1.0,Marketing,2019-07-01 00:00:00,85.73
44,44.0,Anita,NaN,F,NaN,108549,29.0,NaN,2019-11-0,46.92
45,45.0,NaN,NaN,NaN,Mumbai,"₹117,161",25.0,HR,04-09-201,93.75
46,46.0,Priya,NaN,Male,HYD,27431,18.0,HR,2021-05-27 00:00:00,NaN

In [6]:
df.sample(15, random_state=1)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score
24,25.0,Arjun,NaN,F,Pune,63771,-2.0,NaN,2018-04-02 00:00:00,74.49
22,23.0,Vijay,NaN,Male,Hyderaba,64791,14.0,IT,2021-05-0,63.78
39,39.0,Anita,NaN,M,Mumbai,63004,6.0,Sales,2019-09-0,45.02
35,NaN,NaN,NaN,NaN,Bangalore,NaN,NaN,NaN,2023-09-29 00:00:00,NaN
2,3.0,Neha,44.0,M,NaN,111831,28.0,IT,2020-06-23 00:00:00,65.04
3,79.0,Sneha,38.0,F,HYD,72973,3.0,HR,2021-01-0,65.51
29,30.0,Vijay,NaN,Unknown,Pune,NaN,8.0,HR,2022-11-0,90.37
32,33.0,Rohit,NaN,F,hyd,90778,4.0,HR,05-05-202,82.34
45,45.0,NaN,NaN,NaN,Mumbai,"₹117,161",25.0,HR,04-09-201,93.75
26,71.0,Rohit,NaN,NaN,Mumbai,91146,11.0,it,2020-07-08 00:00:00,65.76
19,20.0,Rohit,22.0,NaN,Bengaluru,116802,5.0,Sales,2020-05-23 00:00:00,93.24
36,36.0,Amit,NaN,Female,NaN,NaN,24.0,Finance,NaN,NaN
46,46.0,Priya,NaN,Male,HYD,27431,18.0,HR,2021-05-27 00:00:00,NaN
33,34.0,Kiran,NaN,Male,HYD,27928,29.0,Finance,08-30-202,47.11
23,24.0,Ravi,NaN,F,Delhi,63379,2.0,Marketing,2020-06-25 00:00:00,75.77

In [7]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)

Number of rows: 47
Number of columns: 10

Column names: ['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Experience', 'Department', 'Joining_Date', 'Performance_Score']

Data types:
 Customer_ID          float64
Name                  object
Age                  float64
Gender                object
City                  object
Salary                object
Experience           float64
Department            object
Joining_Date          object
Performance_Score    float64
dtype: object

In [8]:
df.isnull().sum()

Customer_ID           1
Name                  4
Age                  27
Gender                6
City                  8
Salary                4
Experience            2
Department            6
Joining_Date          1
Performance_Score     3
dtype: int64

In [9]:
df[df['Name'].isnull()]

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score
7,8.0,NaN,22.0,M,Chennai,"₹58,457",5.0,it,2024-10-0,96.17
25,26.0,NaN,NaN,Female,Hyderabad,NaN,12.0,hr,2020-06-01 00:00:00,88.03
35,NaN,NaN,NaN,NaN,Bangalore,NaN,NaN,NaN,2023-09-29 00:00:00,NaN
45,45.0,NaN,NaN,NaN,Mumbai,"₹117,161",25.0,HR,04-09-201,93.75

In [10]:
df['Name'] = df['Name'].fillna('Unknown')
df['City'] = df['City'].fillna('Not Available')
df['Department'] = df['Department'].fillna('Not Assigned')

df.isnull().sum()

Customer_ID           1
Name                  0
Age                  27
Gender                6
City                  0
Salary                4
Experience            2
Department            0
Joining_Date          1
Performance_Score     3
dtype: int64

In [11]:
print("Number of fully duplicate rows:", df.duplicated().sum())

Number of fully duplicate rows: 0

In [12]:
print("Number of duplicate Customer_ID values:", df['Customer_ID'].duplicated().sum())
df[df['Customer_ID'].duplicated(keep=False)]

Number of duplicate Customer_ID values: 1

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score
3,79.0,Sneha,38.0,F,HYD,72973,3.0,HR,2021-01-0,65.51
37,79.0,Pooja,NaN,NaN,hyd,110730,28.0,it,2022-01-01 00:00:00,62.01

In [13]:
df = df.drop_duplicates(subset='Customer_ID', keep='first')
print("Shape after removing duplicate Customer_IDs:", df.shape)

Shape after removing duplicate Customer_IDs: (46, 10)

In [14]:
df['Name'] = df['Name'].astype(str).str.strip()
df['Name'].head(10)

0       Amit
1      Kiran
2       Neha
3      Sneha
4      Rohit
5      Pooja
6       Neha
7    Unknown
8      Pooja
9      Kiran
Name: Name, dtype: object

In [15]:
print("Before:", df['Gender'].unique())

def clean_gender(x):
    if pd.isna(x):
        return 'Unknown'
    x = str(x).strip().lower()
    if x in ['m', 'male']:
        return 'Male'
    if x in ['f', 'female']:
        return 'Female'
    return 'Unknown'

df['Gender'] = df['Gender'].apply(clean_gender)
print("After:", df['Gender'].unique())
df['Gender'].value_counts()

Before: ['Female' 'F' 'M' 'Unknown' nan 'Male']
After: ['Female' 'Male' 'Unknown']

Gender
Female     20
Male       13
Unknown    13
Name: count, dtype: int64

In [16]:
print("Before:", df['City'].unique())

def clean_city(x):
    if pd.isna(x):
        return x
    x = str(x).strip().lower()
    mapping = {
        'hyd': 'Hyderabad', 'hyderabad': 'Hyderabad', 'hyderaba': 'Hyderabad',
        'bangalore': 'Bengaluru', 'bengaluru': 'Bengaluru',
        'chennai': 'Chennai', 'delhi': 'Delhi', 'mumbai': 'Mumbai', 'pune': 'Pune',
        'not available': 'Not Available'
    }
    return mapping.get(x, x.title())

df['City'] = df['City'].apply(clean_city)
print("After:", df['City'].unique())
df['City'].value_counts()

Before: ['Chennai' 'Bengaluru' 'Not Available' 'HYD' 'hyd' 'Delhi' 'Bangalore'
 'Mumbai' 'Pune' 'Hyderaba' 'Hyderabad']
After: ['Chennai' 'Bengaluru' 'Not Available' 'Hyderabad' 'Delhi' 'Mumbai' 'Pune']

City
Hyderabad        12
Bengaluru         8
Not Available     8
Pune              6
Delhi             5
Mumbai            4
Chennai           3
Name: count, dtype: int64

In [17]:
print("Before:", df['Salary'].unique()[:10])

df['Salary'] = (df['Salary'].astype(str)
                .str.replace('₹', '', regex=False)
                .str.replace(',', '', regex=False))
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

print("\nDtype after cleaning:", df['Salary'].dtype)
df['Salary'].head(10)

Before: [48886 '₹75,196' 111831 72973 64961 38199 31152 '₹58,457' 93372 59378]

Dtype after cleaning: float64

0     48886.0
1     75196.0
2    111831.0
3     72973.0
4     64961.0
5     38199.0
6     31152.0
7     58457.0
8     93372.0
9     59378.0
Name: Salary, dtype: float64

In [18]:
for col in ['Age', 'Salary', 'Experience', 'Performance_Score']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

Customer_ID          float64
Name                  object
Age                  float64
Gender                object
City                  object
Salary               float64
Experience           float64
Department            object
Joining_Date          object
Performance_Score    float64
dtype: object

In [19]:
invalid_age = df[(df['Age'] < 18) | (df['Age'] > 100)]
print("Invalid age rows:")
display(invalid_age[['Customer_ID', 'Name', 'Age']])

df.loc[(df['Age'] < 18) | (df['Age'] > 100), 'Age'] = np.nan
df['Age'].describe()

Invalid age rows:

   Customer_ID   Name  Age
8          9.0  Pooja -5.0

count    19.000000
mean     38.578947
std      13.305453
min      20.000000
25%      28.500000
50%      38.000000
75%      49.000000
max      59.000000
Name: Age, dtype: float64

In [20]:
negative_exp = df[df['Experience'] < 0]
print("Rows with negative experience:")
display(negative_exp[['Customer_ID', 'Name', 'Experience']])

df.loc[df['Experience'] < 0, 'Experience'] = 0
print("\nMinimum experience after fix:", df['Experience'].min())

Rows with negative experience:

    Customer_ID   Name  Experience
24         25.0  Arjun        -2.0

Minimum experience after fix: 0.0

In [21]:
def detect_outliers_iqr(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = series[(series < lower) | (series > upper)]
    return outliers, lower, upper

for col in ['Salary', 'Performance_Score']:
    outliers, lower, upper = detect_outliers_iqr(df[col].dropna())
    print(f"{col}: lower bound={lower:.2f}, upper bound={upper:.2f}")
    print(f"  Outlier values: {outliers.tolist()}\n")

Salary: lower bound=-16697.00, upper bound=158523.00
  Outlier values: []

Performance_Score: lower bound=25.92, upper bound=126.17
  Outlier values: []

In [22]:
for col in ['Salary', 'Performance_Score']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower=lower, upper=upper)

df[['Salary', 'Performance_Score']].describe()

              Salary  Performance_Score
count      42.000000          43.000000
mean    68566.738095          73.064186
std     28136.063346          16.788479
min     25508.000000          42.720000
25%     49010.500000          63.515000
50%     64281.000000          74.490000
75%     92815.500000          88.575000
max    117161.000000          98.680000

In [23]:
print("Sample raw values:", df['Joining_Date'].unique()[:8])

df['Joining_Date'] = pd.to_datetime(df['Joining_Date'], errors='coerce')

print("\nInvalid/unparseable dates (now NaT):", df['Joining_Date'].isnull().sum())
df['Joining_Date'].head(10)

Sample raw values: [datetime.datetime(2020, 2, 9, 0, 0) datetime.datetime(2020, 4, 1, 0, 0)
 datetime.datetime(2020, 6, 23, 0, 0) '2021-01-0'
 datetime.datetime(2020, 3, 28, 0, 0) datetime.datetime(2019, 3, 2, 0, 0)
 datetime.datetime(2020, 12, 31, 0, 0) '2024-10-0']

Invalid/unparseable dates (now NaT): 14

0   2020-02-09
1   2020-04-01
2   2020-06-23
3          NaT
4   2020-03-28
5   2019-03-02
6   2020-12-31
7          NaT
8   2020-07-12
9   2020-04-11
Name: Joining_Date, dtype: datetime64[ns]

In [24]:
df['Joining_Year'] = df['Joining_Date'].dt.year
df['Joining_Month'] = df['Joining_Date'].dt.month
df['Joining_Day'] = df['Joining_Date'].dt.day

df[['Joining_Date', 'Joining_Year', 'Joining_Month', 'Joining_Day']].head(10)

  Joining_Date  Joining_Year  Joining_Month  Joining_Day
0   2020-02-09        2020.0            2.0          9.0
1   2020-04-01        2020.0            4.0          1.0
2   2020-06-23        2020.0            6.0         23.0
3          NaT           NaN            NaN          NaN
4   2020-03-28        2020.0            3.0         28.0
5   2019-03-02        2019.0            3.0          2.0
6   2020-12-31        2020.0           12.0         31.0
7          NaT           NaN            NaN          NaN
8   2020-07-12        2020.0            7.0         12.0
9   2020-04-11        2020.0            4.0         11.0

In [25]:
def clean_loan_status(x):
    if pd.isna(x):
        return x
    x = str(x).strip().lower()
    if x in ['y', 'yes']:
        return 'Yes'
    if x in ['n', 'no']:
        return 'No'
    return x

if 'Loan_Status' in df.columns:
    df['Loan_Status'] = df['Loan_Status'].apply(clean_loan_status)
    print(df['Loan_Status'].unique())
else:
    print("No 'Loan_Status' column in this dataset — skipped.")

No 'Loan_Status' column in this dataset — skipped.

In [26]:
if 'Rating' in df.columns:
    invalid_rating = df[(df['Rating'] < 1) | (df['Rating'] > 5)]
    print(invalid_rating)
    df.loc[(df['Rating'] < 1) | (df['Rating'] > 5), 'Rating'] = np.nan
else:
    print("No 'Rating' column in this dataset — skipped.")

No 'Rating' column in this dataset — skipped.

In [30]:
def clean_employee_data(path):
    df = pd.read_excel(path)

    # Fix shifted header
    df = df.drop(columns=['Age']).rename(columns={'Unnamed: 3': 'Age'})
    df = df.rename(columns={
        'Customer': 'Customer_ID', 'Experienc': 'Experience',
        'Departme': 'Department', 'Joining_D': 'Joining_Date',
        'Performa': 'Performance_Score'
    })
    df = df[['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary',
              'Experience', 'Department', 'Joining_Date', 'Performance_Score']]

    # Handle missing values
    df['Name'] = df['Name'].fillna('Unknown')
    df['City'] = df['City'].fillna('Not Available')
    df['Department'] = df['Department'].fillna('Not Assigned')

    # Remove duplicates
    df = df.drop_duplicates(subset='Customer_ID', keep='first')

    # Clean strings
    df['Name'] = df['Name'].astype(str).str.strip()

    def clean_gender(x):
        if pd.isna(x): return 'Unknown'
        x = str(x).strip().lower()
        if x in ['m', 'male']: return 'Male'
        if x in ['f', 'female']: return 'Female'
        return 'Unknown'
    df['Gender'] = df['Gender'].apply(clean_gender)

    def clean_city(x):
        if pd.isna(x): return x
        x = str(x).strip().lower()
        mapping = {'hyd': 'Hyderabad', 'hyderabad': 'Hyderabad', 'hyderaba': 'Hyderabad',
                   'bangalore': 'Bengaluru', 'bengaluru': 'Bengaluru', 'chennai': 'Chennai',
                   'delhi': 'Delhi', 'mumbai': 'Mumbai', 'pune': 'Pune',
                   'not available': 'Not Available'}
        return mapping.get(x, x.title())
    df['City'] = df['City'].apply(clean_city)

    def clean_dept(x):
        if pd.isna(x): return x
        x = str(x).strip()
        mapping = {'it': 'IT', 'hr': 'HR', 'finance': 'Finance',
                   'sales': 'Sales', 'marketing': 'Marketing',
                   'not assigned': 'Not Assigned'}
        return mapping.get(x.lower(), x.title())
    df['Department'] = df['Department'].apply(clean_dept)

    # Clean Salary
    df['Salary'] = (df['Salary'].astype(str)
                     .str.replace('₹', '', regex=False)
                     .str.replace(',', '', regex=False))

    # Convert datatypes
    for col in ['Age', 'Salary', 'Experience', 'Performance_Score']:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Fix invalid values
    df.loc[(df['Age'] < 18) | (df['Age'] > 100), 'Age'] = np.nan
    df.loc[df['Experience'] < 0, 'Experience'] = 0

    # Handle outliers (cap using IQR)
    for col in ['Salary', 'Performance_Score']:
        Q1, Q3 = df[col].quantile(0.25), df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        df[col] = df[col].clip(lower=lower, upper=upper)

    # Dates + feature engineering
    df['Joining_Date'] = pd.to_datetime(df['Joining_Date'], errors='coerce')
    df['Joining_Year'] = df['Joining_Date'].dt.year
    df['Joining_Month'] = df['Joining_Date'].dt.month
    df['Joining_Day'] = df['Joining_Date'].dt.day

    return df

df_clean = clean_employee_data("D:\Data science\Datasets\Pandas_Practice_Dataset.xlsx")
df_clean.head(10)

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Joining_Year,Joining_Month,Joining_Day
0,1.0,Amit,43.0,Female,Chennai,48886.0,26.0,Not Assigned,2020-02-09,90.81,2020.0,2.0,9.0
1,2.0,Kiran,35.0,Female,Bengaluru,75196.0,14.0,Not Assigned,2020-04-01,70.98,2020.0,4.0,1.0
2,3.0,Neha,44.0,Male,Not Available,111831.0,28.0,IT,2020-06-23,65.04,2020.0,6.0,23.0
3,79.0,Sneha,38.0,Female,Hyderabad,72973.0,3.0,HR,NaT,65.51,NaN,NaN,NaN
4,5.0,Rohit,46.0,Female,Hyderabad,64961.0,17.0,HR,2020-03-28,98.68,2020.0,3.0,28.0
5,6.0,Pooja,28.0,Female,Delhi,38199.0,27.0,HR,2019-03-02,96.75,2019.0,3.0,2.0
6,7.0,Neha,59.0,Female,Bengaluru,31152.0,27.0,Not Assigned,2020-12-31,68.06,2020.0,12.0,31.0
7,8.0,Unknown,22.0,Male,Chennai,58457.0,5.0,IT,NaT,96.17,NaN,NaN,NaN
8,9.0,Pooja,NaN,Unknown,Not Available,93372.0,5.0,Finance,2020-07-12,79.14,2020.0,7.0,12.0
9,10.0,Kiran,58.0,Female,Not Available,59378.0,17.0,IT,2020-04-11,98.43,2020.0,4.0,11.0

In [31]:
print("Highest Salary:", df_clean['Salary'].max())
print("Lowest Salary:", df_clean['Salary'].min())
print("Average Salary:", round(df_clean['Salary'].mean(), 2))
print("Median Salary:", df_clean['Salary'].median())

Highest Salary: 117161.0
Lowest Salary: 25508.0
Average Salary: 68566.74
Median Salary: 64281.0

In [32]:
print("Average Salary by Department:")
display(df_clean.groupby('Department')['Salary'].mean().round(2))

print("\nAverage Performance Score by Gender:")
display(df_clean.groupby('Gender')['Performance_Score'].mean().round(2))

print("\nEmployee count by City:")
display(df_clean.groupby('City').size())

Average Salary by Department:

Department
Finance         55231.80
HR              59959.91
IT              75767.23
Marketing       74882.50
Not Assigned    65510.80
Sales           83006.75
Name: Salary, dtype: float64

Average Performance Score by Gender:

Gender
Female     75.78
Male       61.12
Unknown    80.71
Name: Performance_Score, dtype: float64

Employee count by City:

City
Bengaluru         8
Chennai           3
Delhi             5
Hyderabad        12
Mumbai            4
Not Available     8
Pune              6
dtype: int64

In [33]:
df_clean.to_excel('cleaned_employee_data.xlsx', index=False)
print("Saved cleaned_employee_data.xlsx")

Saved cleaned_employee_data.xlsx

In [34]:
df_clean.columns = df_clean.columns.str.lower().str.replace(' ', '_')
df_clean.columns.tolist()

['customer_id',
 'name',
 'age',
 'gender',
 'city',
 'salary',
 'experience',
 'department',
 'joining_date',
 'performance_score',
 'joining_year',
 'joining_month',
 'joining_day']

In [35]:
obj_cols = df_clean.select_dtypes(include='object').columns
for col in obj_cols:
    df_clean[col] = df_clean[col].replace(r'^\s*$', np.nan, regex=True)

df_clean[obj_cols].isnull().sum()

name          0
gender        0
city          0
department    0
dtype: int64

In [36]:
def age_group(age):
    if pd.isna(age):
        return np.nan
    if age <= 30:
        return 'Young'
    elif age <= 45:
        return 'Mid'
    else:
        return 'Senior'

df_clean['age_group'] = df_clean['age'].apply(age_group)
df_clean[['age', 'age_group']].head(10)

    age age_group
0  43.0       Mid
1  35.0       Mid
2  44.0       Mid
3  38.0       Mid
4  46.0    Senior
5  28.0     Young
6  59.0    Senior
7  22.0     Young
8   NaN       NaN
9  58.0    Senior

In [37]:
df_clean = df_clean.sort_values('salary', ascending=False)
df_clean[['customer_id', 'name', 'salary']].head(10)

    customer_id     name    salary
45         45.0  Unknown  117161.0
19         20.0    Rohit  116802.0
2           3.0     Neha  111831.0
16         17.0    Priya  110640.0
44         44.0    Anita  108549.0
11         12.0    Anita  102686.0
20         21.0    Arjun  101983.0
28         29.0     Neha   99201.0
27         28.0    Arjun   98135.0
14         15.0    Rahul   97298.0

In [38]:
df_clean = df_clean.reset_index(drop=True)
df_clean.head()

,customer_id,name,age,gender,city,salary,experience,department,joining_date,performance_score,joining_year,joining_month,joining_day,age_group
0,45.0,Unknown,NaN,Unknown,Mumbai,117161.0,25.0,HR,NaT,93.75,NaN,NaN,NaN,NaN
1,20.0,Rohit,22.0,Unknown,Bengaluru,116802.0,5.0,Sales,2020-05-23,93.24,2020.0,5.0,23.0,Young
2,3.0,Neha,44.0,Male,Not Available,111831.0,28.0,IT,2020-06-23,65.04,2020.0,6.0,23.0,Mid
3,17.0,Priya,29.0,Male,Chennai,110640.0,23.0,IT,2020-01-01,74.57,2020.0,1.0,1.0,Young
4,44.0,Anita,NaN,Female,Not Available,108549.0,29.0,Not Assigned,NaT,46.92,NaN,NaN,NaN,NaN

In [39]:
print("Duplicate customer_id count:", df_clean['customer_id'].duplicated().sum())

Duplicate customer_id count: 0

In [40]:
print("Ages outside 18-100:", df_clean[(df_clean['age'] < 18) | (df_clean['age'] > 100)].shape[0])
print("Negative experience rows:", df_clean[df_clean['experience'] < 0].shape[0])

Ages outside 18-100: 0
Negative experience rows: 0

In [41]:
df_clean.to_csv('cleaned_employee_data.csv', index=False)
df_clean.to_excel('cleaned_employee_data.xlsx', index=False)
print("Exported cleaned_employee_data.csv and cleaned_employee_data.xlsx")

Exported cleaned_employee_data.csv and cleaned_employee_data.xlsx